# Generated by Django 4.1.5 on 2023-01-30 06:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TransactionFIles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upload", models.FileField(upload_to="transactions/uploads/")),
            ],
        ),
        migrations.CreateModel(
            name="Transactions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            (1, "Débito"),
                            (2, "Boleto"),
                            (3, "Financiamento"),
                            (4, "Crédito"),
                            (5, "Recebimento Empréstimo"),
                            (6, "Vendas"),
                            (7, "Recebimento TED"),
                            (8, "Recebimento DOC"),
                            (9, "Aluguel"),
                        ],
                        default=1,
                        max_length=1,
                    ),
                ),
                ("date", models.DateField()),
                ("value", models.CharField(max_length=10)),
                ("cpf", models.CharField(max_length=11)),
                ("credit_card", models.CharField(max_length=12)),
                ("attendance_hour", models.TimeField()),
                ("shop_owner", models.CharField(max_length=14)),
                ("shop_name", models.CharField(max_length=19)),
            ],
        ),
    ]
