# Generated by Django 4.1.5 on 2023-01-28 21:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TransactionFIles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upload", models.FileField(upload_to="uploads/")),
            ],
        ),
        migrations.CreateModel(
            name="Transactions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("type", models.IntegerField()),
                ("date", models.IntegerField()),
                ("value", models.IntegerField()),
                ("cpf", models.IntegerField()),
                ("credit_card", models.IntegerField()),
                ("attendance_hour", models.IntegerField()),
                ("shop_owner", models.CharField(max_length=14)),
                ("shop_name", models.CharField(max_length=19)),
            ],
        ),
    ]
